# Generated by Django 4.2 on 2024-12-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Portuguese', 'Portuguese'), ('Roman', 'Roman'), ('Russian', 'Russian'), ('Swedish', 'Swedish'), ('Hindi', 'Hindi'), ('Punjabi', 'Punjabi'), ('Marathi', 'Marathi')], max_length=20)),
            ],
            options={
                'db_table': 'temp2',
            },
        ),
    ]
