# Generated by Django 4.2 on 2025-01-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp2',
            name='block',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='district',
        ),
        migrations.RemoveField(
            model_name='temp2',
            name='state',
        ),
        migrations.AddField(
            model_name='temp2',
            name='country',
            field=models.CharField(choices=[('US', 'USA'), ('UK', 'UK'), ('India', 'India'), ('Japan', 'Japan')], default='India', max_length=50),
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.temp2')),
            ],
        ),
        migrations.CreateModel(
            name='districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('Delhi', 'Central Delhi'), ('Delhi', 'East Delhi'), ('Delhi', 'North Delhi'), ('Delhi', 'North East Delhi'), ('Delhi', 'North West Delhi'), ('Delhi', 'Shahdara'), ('Delhi', 'South Delhi'), ('Delhi', 'South East Delhi'), ('Delhi', 'South West Delhi'), ('Delhi', 'West Delhi'), ('Haryana', 'Ambala'), ('Haryana', 'Bhiwani'), ('Haryana', 'Charkhi Dadri'), ('Haryana', 'Faridabad'), ('Haryana', 'Fatehabad'), ('Haryana', 'Gurugram'), ('Haryana', 'Hisar'), ('Haryana', 'Jhajjar'), ('Haryana', 'Jind'), ('Haryana', 'Kaithal'), ('Haryana', 'Karnal'), ('Haryana', 'Kurukshetra'), ('Haryana', 'Mahendragarh'), ('Haryana', 'Nuh'), ('Haryana', 'Palwal'), ('Haryana', 'Panchkula'), ('Haryana', 'Panipat'), ('Haryana', 'Rewari'), ('Haryana', 'Rohtak'), ('Haryana', 'Sirsa'), ('Haryana', 'Sonipat'), ('Haryana', 'Yamunanagar'), ('Punjab', 'Amritsar'), ('Punjab', 'Barnala'), ('Punjab', 'Bathinda'), ('Punjab', 'Faridkot'), ('Punjab', 'Fatehgarh Sahib'), ('Punjab', 'Fazilka'), ('Punjab', 'Ferozepur'), ('Punjab', 'Gurdaspur'), ('Punjab', 'Hoshiarpur'), ('Punjab', 'Jalandhar'), ('Punjab', 'Kapurthala'), ('Punjab', 'Ludhiana'), ('Punjab', 'Malerkotla'), ('Punjab', 'Mansa'), ('Punjab', 'Moga'), ('Punjab', 'Pathankot'), ('Punjab', 'Patiala'), ('Punjab', 'Rupnagar'), ('Punjab', 'Sahibzada Ajit Singh Nagar'), ('Punjab', 'Sangrur'), ('Punjab', 'Shahid Bhagat Singh Nagar'), ('Punjab', 'Sri Muktsar Sahib'), ('Punjab', 'Tarn Taran'), ('Goa', 'North Goa'), ('Goa', 'South Goa'), ('Sikkim', 'East Sikkim'), ('Sikkim', 'North Sikkim'), ('Sikkim', 'South Sikkim'), ('Sikkim', 'West Sikkim'), ('Sikkim', 'Soreng'), ('Sikkim', 'Pakyong'), ('tokyo', 'Hokkaido'), ('texas', 'district'), ('queensland', 'district')], max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.states')),
            ],
        ),
    ]
