# Generated by Django 4.2 on 2025-01-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_remove_temp2_block_remove_temp2_district_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='districts',
            table='districts',
        ),
        migrations.AlterModelTable(
            name='states',
            table='states',
        ),
    ]
