# Generated by Django 4.2 on 2025-01-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_districts_table_alter_states_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='state',
            field=models.CharField(choices=[('India', 'Delhi'), ('India', 'Punjab'), ('India', 'Sikkim'), ('India', 'Goa'), ('India', 'Haryana'), ('US', 'Texas'), ('UK', 'queensland'), ('Japan', 'tokyo')], default='Delhi', max_length=20),
            preserve_default=False,
        ),
    ]
