# Generated by Django 4.2 on 2025-01-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_states_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='state',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='app2.states'),
        ),
        migrations.AlterField(
            model_name='states',
            name='country',
            field=models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='app2.temp2'),
        ),
        migrations.AlterField(
            model_name='temp2',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
