# Generated by Django 4.2 on 2025-01-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_districts_state_alter_states_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
