# Generated by Django 4.2 on 2025-01-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='country',
            field=models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, to='app2.country'),
        ),
        migrations.AlterField(
            model_name='states',
            name='state',
            field=models.CharField(choices=[('India', 'Delhi'), ('India', 'Punjab'), ('India', 'Sikkim'), ('India', 'Goa'), ('India', 'Haryana'), ('USA', 'Texas'), ('UK', 'queensland'), ('Japan', 'tokyo')], max_length=20),
        ),
    ]
