# Generated by Django 4.2 on 2025-01-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_alter_districts_district_alter_states_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp2',
            name='district',
            field=models.CharField(default='select district', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp2',
            name='state',
            field=models.CharField(default='select state', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='districts',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='states',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
