# Generated by Django 4.2 on 2025-01-07 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_temp2_district_temp2_state_alter_districts_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='app2.temp2')),
            ],
            options={
                'db_table': 'passwords',
            },
        ),
    ]
