# Generated by Django 4.2 on 2025-01-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_passwords_user_id_alter_passwords_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='user_id',
            field=models.ForeignKey(db_column='user_data', default=None, on_delete=django.db.models.deletion.CASCADE, to='app2.temp2'),
        ),
    ]
