# Generated by Django 4.2 on 2025-01-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_remove_passwords_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passwords',
        ),
    ]
