# Generated by Django 4.2 on 2026-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp2',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='temp2',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='temp2',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='temp2',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='temp2',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='temp2',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
